### PR TITLE
Fix unmanaged cluster log verbosity enforcement

### LINKED ISSUE #4413: Unmanaged cluster log level not being enforced
## Bug Report

As noticed in https://github.com/vmware-tanzu/community-edition/pull/4393#pullrequestreview-964773328 the default
logging level of 2 is not being honored. Logging appears to be at level 0, so higher level log output is being skipped
by default.

## Expected Behavior

Default log level should be 2 and log output should only be skipped if user explicitly passes `-v 0`.

## Steps to Reproduce the Bug

`tanzu uc create foo`

### PR DESCRIPTION
**Pull request by stmcginnis**
## What this PR does / why we need it

There were issues with the way log verbosity was being set which caused
the incorrect level to be used, resulting in some expected lines not
printing at the default log level.

This updates the handling to correctly parse and set the level from the
flag. Also some minor refactoring to make it a little easier to
understand.

## Which issue(s) this PR fixes

Fixes: #4413 

## Describe testing done for PR

```
go run . create foo
go run . rm foo
go run . create -v 0 foo
go run . rm -v 0 foo
```

### CODE REVIEW

File: cli/cmd/plugin/unmanaged-cluster/cmd/utils.go [hunk 1]
```diff
@@ -57,6 +59,17 @@ func SetupRootCommand(rootCmd *cobra.Command) {
 	rootCmd.SetHelpTemplate(helpTemplate)
 }
 
+// LoggingVerbosity will get the configured logging level for this command.
+func LoggingVerbosity(cmd *cobra.Command) int {
+	level, err := cmd.Flags().GetInt32("verbose")
```
Comment (stmcginnis) [inline cli/cmd/plugin/unmanaged-cluster/cmd/utils.go:64]: @jpmcb would love to get your cobra expertise to verify this is how this parent flag should be handled. Thanks!

**Review by jpmcb — APPROVED** [review]
Nice!!! This looks good to me
